name: docker-compose-actions-workflow
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'DCOS/**'
      - 'K8s/**'
      - 'load-gen/**'
      - 'OpenShift/**'
      - 'Swarm/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: Log out from Docker Hub
      run: docker logout
